name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Html Deploying to surge
    steps:
    - uses: actions/checkout@v2
  

     
    - name: Deploy to surge
      run: surge ./index.html https://numerous-quicksand.surge.sh/ --token ${{secrets.SURGE_TOKEN}}